### PR TITLE
Replace references of openjdk-systemtest with aqa-systemtest

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Related to https://github.com/adoptium/aqa-systemtest/issues/424

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Hi @llxia , This pr is a replacement fo https://github.com/eclipse-openj9/openj9-systemtest/pull/129 - which didn't contain the latest changes that Keith had delivered to this Repo last week (hence the merge conflicts).  

I ran a sanity check using the latest changes and it looks good: Grinder/15338

Could you please review?

**Comment by Mesbah-Alam** [comment]
Please note this PRs has to merged together with:
https://github.com/adoptium/aqa-tests/pull/2542
https://github.com/adoptium/STF/pull/115
https://github.com/adoptium/aqa-systemtest/pull/425

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
